### PR TITLE
Bug fix. Removed the attempt to access an object with an index.

### PR DESCRIPTION
**Pull request by john-laubscher**
### Description: 
                  --We were unable to view the MyProfile page.

**Invited Collaborator(s) to Review
- Added person to review relating to feature/bug
                     --Jaden, Anthony, Kazden
- If not available, ask another reviewer on team

**What work was done?**
- Describe in detail what's been modified/created
                 -- Got rid of the index--we can't use an index to access an object

**Why was this work done?**
- What is the purpose of the feature?: 
                 --Bug fix--allowed us to view the Myprofile page

**What feature / user story is it for?**
(Link if possible) 
                --As a user, it is important to access the profile page
**Any relevant links or images / screenshots**

### Type of change
Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)
                --Bug fix

Testing
- Has this feature been tested before conflict?
             - Yes it has been tested
- Has this feature been tested after conflict?
              - Yes it has been tested

Change Status
- Completed, ready to review and merge

### Checklist
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- My code has been reviewed by at least one peer
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- There are no merge conflicts

Here is the video explanation: https://www.loom.com/share/00106440754c40f6b3a7ba2cfdf4b5bb

### CODE REVIEW

**Review by Anthony-Cortese — APPROVED** [review]
The update looks simple enough, and we are now able to view the profile page for users, admins, etc. That is great work on finding that bug.

**Comment by LilCthulu** [comment]
Looks good. Nice work!

**Review by KazdenJolley — COMMENTED** [review]
Looks good to me!

**Review by LilCthulu — APPROVED** [review]
Looks good man. Nice work!

**Pull request merged**
