### PR TITLE
Stripping away components from Dashboard

### PR DESCRIPTION
**Pull request by Margarita-Salazar**
### Description

Deleted away unused files/components to set up a clean slate for the rebuild of the Dashboard.

**Invited Collaborator(s) to Review**
- Contact @Chantz-J @JasmineLaneGarcia for more related information
- Added person to review relating to feature/bug
- If not available, ask another reviewer on team

**What work was done?**
- Deleted DashboardServiceTable
- Deleted MyProfile Component
- Commented out the MetricsFilterBar

**Why was this work done?**
- In order to set up for the future rebuilding of the Dashboard

**What feature / user story is it for?**
**Any relevant links or images / screenshots**

**WireFrame of The Dashboard**
- https://whimsical.com/family-promise-W1z8vmBUSmA3mjreyZuFo2

**Trello Card**
- https://trello.com/c/qBBkRRDc/18-as-a-user-i-can-view-relevant-metrics-on-my-dashboard 

### Type of change
Please delete options that are not relevant.
- Refactored feature (non-breaking change)

Testing
- Has this feature been tested before conflict?
- Has this feature been tested after conflict?

Change Status
- Completed, ready to review and merge

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

**Loom Video** 
- https://www.loom.com/share/3a2a0ffdf0a94c20a014c74eb2671757?sharedAppSource=personal_library

### CODE REVIEW

**Review by tommycapello — APPROVED** [review]
Great job clearing out the Dashboard component. It's great that we are moving away from placeholder components and getting closer to rendering the map and other useful user interfaces.

**Review by Anthony-Cortese — APPROVED** [review]
Im excited to see the new implementation to the Dashboard, and this will be a big step in the right direction! This PR looks really good, and I am excited about the future!

**Review by LilCthulu — APPROVED** [review]
Awesome! Now that the placeholder components are gone we can start making strides towards the map!

**Review by JasmineLaneGarcia — COMMENTED** [review]
Nice implementation!

**Pull request merged**
