### PR TITLE
Feature/dashboard/responsive design to metric component

### PR DESCRIPTION
**Pull request by PurdyRad**
### Description

**Invited Collaborator(s) to Review
- Added person to review relating to feature/bug
- If not available, ask another reviewer on team

**What work was done?**
- Describe in detail what's been modified/created
Super simple PR just added some css to the metric component so that it's displayed properly throughout the dashboard.

**Why was this work done?**
- What is the purpose of the feature?
So that the metric component responds to size and stays in center while sizing changes.

**What feature / user story is it for?**
**Any relevant links or images / screenshots**
https://trello.com/c/yIkE9Cq7/53-tablet-view

### Type of change
Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

Testing
- Has this feature been tested before conflict?
- Has this feature been tested after conflict?

Change Status
- Completed, ready to review and merge

### Checklist
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- My code has been reviewed by at least one peer
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- There are no merge conflicts

### CODE REVIEW

**Comment by Jonathan1600** [comment]
I saw that you added a css file into the common components folder and then imported it to the .js component. I would advise you to change it to a scss file and to move it to the style folders to follow the previous code system we have!

**Review by Jonathan1600 — CHANGES_REQUESTED** [review]
I saw that you added a css file into the common components folder and then imported it to the .js component. I would advise you to change it to a scss file and to move it to the style folders to follow the previous code system we have!

**Comment by robertjallen** [comment]
has some merge conflicts

**Review by robertjallen — COMMENTED** [review]
has some merge conflicts

**Comment by PurdyRad** [comment]
> has some merge conflicts

Cleared the conflicts!

**Comment by PurdyRad** [comment]
> I saw that you added a css file into the common components folder and then imported it to the .js component. I would advise you to change it to a scss file and to move it to the style folders to follow the previous code system we have!

Updated the css file to scss and imported it into app.scss to follow previous code system! Thanks for the feedback!

**Pull request merged**
