### PR TITLE
Feature/responsive design/tablet first

### PR DESCRIPTION
**Pull request by Jacobstephens17**
Got tables that are currently displaying to center align and flex correctly (down to around 400px). Also removed some of the padding and margins from the second header that has the buttons in it so they no longer get pushed off the page when the display size is changed. The secondary header needs to be styled better to align center and flex correctly. There shouldn't be any conflicts with these changes. 

Next step is to try and get everything horizontally aligned so that when the menu is opened everything flexes to the right and scales correctly. 

https://user-images.githubusercontent.com/64627086/117883487-4fc75480-b260-11eb-8115-21c401266278.mp4

### CODE REVIEW

**Comment by Jacobstephens17** [comment]
https://user-images.githubusercontent.com/64627086/117894767-e8b29b80-b271-11eb-983a-25f1c94573b3.mp4

Here is a video of the new Horizontal Nav bar

**Review by agoomar — APPROVED** [review]
Responsive design is amazing! Love the hamburger menu that was implemented.

**Comment by Jacobstephens17** [comment]
Here are the changes to the Navbar and the styling that was done for the recipient's page. The design looks good when the display orientation is horizontal but not vertical. Working on getting the table to scale down and fit better without distorting the data it is presenting. There are no current conflicts with the main branch 


https://user-images.githubusercontent.com/64627086/118058299-be7cde80-b342-11eb-9d27-8b5dbf577c1e.mp4

**Review by danielwright1207 — APPROVED** [review]
Hey man this looks great, awesome work and a solid start for tablet first design.

**Comment by jenkrame21** [comment]
Really good job, Jacob! If we could get that Recipients table sorted out vertically, we'll be super good to go. Appreciate your help on tackling this task!

**Pull request merged**
